data/: Fix import_contributors_data command
This fix the import_contributors_data command
when the webservices has a server error and our
returned data by the method get_contrib_data is None,
then while iterating through the contributors data
in the management command we need to first check
if the data is not empty to avoid the error:
TypeError: 'NoneType' object is not iterable

Fixes https://github.com/coala/community/issues/167